console.time('Your code took');
console.log('Hello');
console.log(34+8);
console.log([34,2,4,9]);
console.log({shubham: "this", marks: 34});
console.table({shubham: "this", marks: 34});
console.timeEnd('Your code took');
// age = 200;
console.assert(200<189, "This is wrong");
console.error('This is an error');